on:
  release:
    types: [created]

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            archive_type: zip
            archive_name: heygpt_win64
          - target: x86_64-unknown-linux-musl
            archive_type: tar.gz
            archive_name: heygpt_linux
          - target: x86_64-apple-darwin
            archive_type: zip
            archive_name: heygpt_macos
    steps:
      - uses: actions/checkout@master
      - name: Compile and release
        uses: rust-build/rust-build.action@v1.4.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          RUSTTARGET: ${{ matrix.target }}
          ARCHIVE_TYPES: ${{ matrix.archive_type }}
          ARCHIVE_NAME: ${{ matrix.archive_name }}
